### ISSUE TITLE
Allow user defined `make install` directory

### ISSUE THREAD

**Issue by cstlee** [PlatformLab/PerfUtils#3]
At the moment `make install` adds the libraries and headers to the repository's root directory.  It would be nice if a user could specify an alternative directory.  Some typical ways to do this are to allow the assignment of a `PREFIX` variable or a `DESTDIR` variable (or both).   [RAMCloud](https://github.com/PlatformLab/RAMCloud/blob/master/GNUmakefile#L167) seems to use `INSTALL_DIR`.

**Comment by cstlee** [comment]
@hq6, what do you think?

**Comment by hq6** [comment]
@cstlee I concur. Do you want me to fix it at the next boring talk, or will you create another pull request?
